insert into classes (id, name, schoolyear) values (1, 'France', 2021);
insert into classes (id, name, schoolyear) values (2, 'Thailand', 2022);
insert into classes (id, name, schoolyear) values (3, 'Cocos Islands', 2021);
insert into classes (id, name, schoolyear) values (4, 'France', 2022);
insert into classes (id, name, schoolyear) values (5, 'Philippines', 2022);
insert into classes (id, name, schoolyear) values (6, 'Finland', 2022);
insert into classes (id, name, schoolyear) values (7, 'Albania', 2022);
insert into classes (id, name, schoolyear) values (8, 'Argentina', 2022);
insert into classes (id, name, schoolyear) values (9, 'Russia', 2021);
insert into classes (id, name, schoolyear) values (10, 'Russia', 2021);
insert into classes (id, name, schoolyear) values (11, 'Yemen', 2021);
insert into classes (id, name, schoolyear) values (12, 'Hungary', 2021);
insert into classes (id, name, schoolyear) values (13, 'South Africa', 2021);
insert into classes (id, name, schoolyear) values (14, 'United States', 2021);
insert into classes (id, name, schoolyear) values (15, 'Egypt', 2021);
insert into classes (id, name, schoolyear) values (16, 'Indonesia', 2022);
insert into classes (id, name, schoolyear) values (17, 'China', 2021);
insert into classes (id, name, schoolyear) values (18, 'Brazil', 2022);
insert into classes (id, name, schoolyear) values (19, 'Zambia', 2021);
insert into classes (id, name, schoolyear) values (20, 'Indonesia', 2021);
insert into classes (id, name, schoolyear) values (21, 'Ukraine', 2022);
insert into classes (id, name, schoolyear) values (22, 'Somalia', 2021);
insert into classes (id, name, schoolyear) values (23, 'China', 2021);
insert into classes (id, name, schoolyear) values (24, 'Indonesia', 2021);
insert into classes (id, name, schoolyear) values (25, 'Finland', 2021);
insert into classes (id, name, schoolyear) values (26, 'Czech Republic', 2021);
insert into classes (id, name, schoolyear) values (27, 'Greece', 2021);
insert into classes (id, name, schoolyear) values (28, 'Iraq', 2022);
insert into classes (id, name, schoolyear) values (29, 'Honduras', 2021);
insert into classes (id, name, schoolyear) values (30, 'Russia', 2022);
insert into classes (id, name, schoolyear) values (31, 'Greece', 2022);
insert into classes (id, name, schoolyear) values (32, 'China', 2021);
insert into classes (id, name, schoolyear) values (33, 'Indonesia', 2022);
insert into classes (id, name, schoolyear) values (34, 'China', 2022);
insert into classes (id, name, schoolyear) values (35, 'China', 2021);
insert into classes (id, name, schoolyear) values (36, 'Peru', 2021);
insert into classes (id, name, schoolyear) values (37, 'Kiribati', 2022);
insert into classes (id, name, schoolyear) values (38, 'Indonesia', 2021);
insert into classes (id, name, schoolyear) values (39, 'Chile', 2021);
insert into classes (id, name, schoolyear) values (40, 'China', 2021);
insert into classes (id, name, schoolyear) values (41, 'Marshall Islands', 2021);
insert into classes (id, name, schoolyear) values (42, 'Canada', 2021);
insert into classes (id, name, schoolyear) values (43, 'Indonesia', 2022);
insert into classes (id, name, schoolyear) values (44, 'Colombia', 2021);
insert into classes (id, name, schoolyear) values (45, 'Myanmar', 2022);
insert into classes (id, name, schoolyear) values (46, 'France', 2021);
insert into classes (id, name, schoolyear) values (47, 'China', 2022);
insert into classes (id, name, schoolyear) values (48, 'Indonesia', 2021);
insert into classes (id, name, schoolyear) values (49, 'France', 2022);
insert into classes (id, name, schoolyear) values (50, 'Belgium', 2022);
