- name: Copy folder content recursively to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: /
          remote: test/
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
