insert into house_staff (id, house_id, staff_id, function, schoolyear) values (1, 5, 258, 'General Manager', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (2, 1, 195, 'Nurse', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (3, 10, 446, 'Senior Developer', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (4, 3, 385, 'Software Test Engineer IV', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (5, 1, 376, 'Librarian', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (6, 5, 83, 'Tax Accountant', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (7, 9, 84, 'Account Executive', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (8, 5, 479, 'Actuary', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (9, 6, 111, 'Data Coordiator', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (10, 3, 339, 'Recruiter', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (11, 5, 65, 'Health Coach III', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (12, 1, 305, 'Geological Engineer', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (13, 10, 266, 'Project Manager', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (14, 1, 269, 'Compensation Analyst', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (15, 3, 317, 'Nurse Practicioner', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (16, 1, 480, 'Computer Systems Analyst III', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (17, 9, 348, 'Assistant Media Planner', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (18, 8, 345, 'Systems Administrator II', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (19, 6, 127, 'Assistant Media Planner', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (20, 5, 276, 'Tax Accountant', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (21, 5, 93, 'Account Executive', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (22, 4, 398, 'Computer Systems Analyst IV', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (23, 3, 40, 'General Manager', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (24, 2, 405, 'Paralegal', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (25, 10, 187, 'Nurse', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (26, 3, 362, 'Actuary', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (27, 3, 379, 'Developer III', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (28, 3, 195, 'General Manager', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (29, 4, 164, 'Graphic Designer', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (30, 10, 456, 'Pharmacist', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (31, 1, 426, 'Health Coach IV', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (32, 4, 88, 'Computer Systems Analyst III', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (33, 7, 426, 'Payment Adjustment Coordinator', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (34, 3, 197, 'Environmental Specialist', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (35, 5, 448, 'Technical Writer', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (36, 7, 162, 'Clinical Specialist', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (37, 8, 249, 'Engineer I', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (38, 2, 6, 'Software Consultant', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (39, 10, 378, 'Librarian', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (40, 10, 477, 'Tax Accountant', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (41, 3, 448, 'Structural Engineer', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (42, 9, 13, 'Software Consultant', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (43, 8, 231, 'Senior Editor', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (44, 2, 309, 'Junior Executive', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (45, 4, 52, 'Database Administrator III', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (46, 3, 232, 'Database Administrator III', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (47, 3, 82, 'Quality Control Specialist', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (48, 5, 2, 'Technical Writer', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (49, 9, 179, 'Environmental Tech', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (50, 10, 490, 'Accountant IV', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (51, 5, 36, 'Senior Developer', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (52, 10, 473, 'VP Product Management', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (53, 1, 239, 'Geologist III', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (54, 4, 407, 'Media Manager III', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (55, 7, 39, 'VP Product Management', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (56, 7, 240, 'Financial Advisor', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (57, 2, 96, 'Software Engineer IV', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (58, 3, 96, 'Actuary', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (59, 3, 177, 'Physical Therapy Assistant', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (60, 8, 35, 'Nurse', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (61, 7, 64, 'Nurse Practicioner', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (62, 8, 263, 'Executive Secretary', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (63, 7, 192, 'Senior Sales Associate', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (64, 10, 286, 'Director of Sales', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (65, 3, 32, 'Registered Nurse', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (66, 3, 309, 'VP Sales', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (67, 6, 460, 'Account Executive', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (68, 3, 165, 'Staff Scientist', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (69, 10, 134, 'Biostatistician I', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (70, 8, 138, 'Analyst Programmer', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (71, 4, 422, 'Actuary', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (72, 8, 86, 'Operator', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (73, 7, 349, 'Senior Sales Associate', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (74, 1, 171, 'Developer IV', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (75, 10, 292, 'Web Designer II', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (76, 6, 101, 'Assistant Media Planner', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (77, 10, 85, 'Recruiter', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (78, 2, 58, 'Web Designer IV', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (79, 2, 471, 'Help Desk Operator', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (80, 2, 108, 'Information Systems Manager', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (81, 8, 218, 'Paralegal', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (82, 7, 108, 'Operator', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (83, 6, 499, 'Help Desk Operator', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (84, 9, 435, 'VP Quality Control', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (85, 8, 16, 'Operator', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (86, 5, 30, 'Community Outreach Specialist', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (87, 8, 314, 'Senior Cost Accountant', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (88, 1, 89, 'Executive Secretary', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (89, 6, 432, 'Account Coordinator', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (90, 9, 32, 'Sales Representative', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (91, 2, 328, 'Nurse', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (92, 6, 459, 'Administrative Assistant III', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (93, 10, 319, 'Mechanical Systems Engineer', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (94, 6, 30, 'Environmental Specialist', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (95, 8, 189, 'Web Designer IV', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (96, 5, 191, 'Accountant I', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (97, 4, 10, 'Teacher', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (98, 9, 15, 'Developer II', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (99, 1, 158, 'Technical Writer', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (100, 2, 77, 'Senior Editor', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (101, 10, 499, 'Professor', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (102, 6, 231, 'Design Engineer', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (103, 8, 11, 'Structural Engineer', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (104, 10, 49, 'Geological Engineer', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (105, 1, 268, 'Geologist I', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (106, 7, 58, 'Budget/Accounting Analyst I', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (107, 4, 433, 'Research Assistant III', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (108, 3, 443, 'Food Chemist', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (109, 7, 435, 'Health Coach II', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (110, 1, 85, 'Research Assistant IV', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (111, 6, 16, 'GIS Technical Architect', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (112, 5, 6, 'Actuary', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (113, 9, 182, 'Information Systems Manager', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (114, 10, 241, 'Web Designer II', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (115, 1, 169, 'Budget/Accounting Analyst II', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (116, 5, 36, 'Staff Scientist', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (117, 4, 152, 'Budget/Accounting Analyst IV', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (118, 1, 6, 'Accountant IV', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (119, 6, 402, 'Quality Engineer', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (120, 2, 315, 'Administrative Assistant IV', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (121, 7, 381, 'Librarian', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (122, 5, 157, 'Quality Control Specialist', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (123, 5, 299, 'Human Resources Assistant I', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (124, 7, 378, 'Occupational Therapist', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (125, 3, 276, 'Teacher', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (126, 5, 445, 'Web Developer III', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (127, 1, 407, 'Chief Design Engineer', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (128, 3, 338, 'Electrical Engineer', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (129, 1, 243, 'Web Developer III', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (130, 7, 148, 'Financial Analyst', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (131, 9, 386, 'Payment Adjustment Coordinator', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (132, 3, 121, 'Help Desk Operator', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (133, 10, 301, 'Biostatistician III', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (134, 9, 160, 'General Manager', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (135, 10, 371, 'Office Assistant II', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (136, 6, 207, 'Senior Quality Engineer', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (137, 3, 347, 'General Manager', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (138, 6, 42, 'Human Resources Manager', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (139, 10, 487, 'Analog Circuit Design manager', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (140, 6, 68, 'Nurse Practicioner', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (141, 9, 155, 'Assistant Professor', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (142, 5, 116, 'Product Engineer', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (143, 8, 100, 'Programmer I', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (144, 7, 196, 'Research Associate', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (145, 2, 164, 'Health Coach III', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (146, 8, 262, 'Senior Editor', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (147, 7, 248, 'Technical Writer', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (148, 6, 116, 'Staff Accountant IV', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (149, 6, 147, 'Physical Therapy Assistant', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (150, 4, 53, 'Environmental Tech', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (151, 5, 488, 'Data Coordiator', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (152, 4, 497, 'Structural Engineer', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (153, 8, 415, 'Administrative Assistant III', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (154, 5, 439, 'Recruiting Manager', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (155, 9, 258, 'Dental Hygienist', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (156, 5, 286, 'Chief Design Engineer', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (157, 4, 31, 'Pharmacist', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (158, 9, 377, 'Registered Nurse', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (159, 6, 176, 'Nurse', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (160, 4, 299, 'Senior Sales Associate', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (161, 2, 483, 'Account Executive', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (162, 5, 326, 'Physical Therapy Assistant', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (163, 6, 10, 'Research Associate', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (164, 3, 47, 'Electrical Engineer', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (165, 9, 46, 'Staff Scientist', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (166, 3, 300, 'Software Test Engineer I', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (167, 9, 8, 'Help Desk Operator', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (168, 1, 203, 'Data Coordiator', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (169, 6, 1, 'Marketing Manager', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (170, 7, 117, 'Sales Associate', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (171, 5, 244, 'Business Systems Development Analyst', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (172, 4, 204, 'Chemical Engineer', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (173, 5, 102, 'Director of Sales', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (174, 2, 468, 'Social Worker', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (175, 7, 123, 'VP Product Management', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (176, 8, 231, 'Associate Professor', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (177, 9, 175, 'Research Assistant II', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (178, 1, 247, 'Internal Auditor', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (179, 1, 372, 'Environmental Specialist', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (180, 3, 485, 'Structural Analysis Engineer', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (181, 1, 176, 'Structural Engineer', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (182, 5, 372, 'Structural Analysis Engineer', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (183, 6, 304, 'Structural Analysis Engineer', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (184, 3, 147, 'Programmer Analyst IV', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (185, 7, 7, 'Senior Editor', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (186, 10, 37, 'GIS Technical Architect', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (187, 8, 190, 'Registered Nurse', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (188, 7, 36, 'Social Worker', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (189, 10, 112, 'Developer I', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (190, 9, 332, 'Senior Developer', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (191, 7, 24, 'Cost Accountant', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (192, 1, 47, 'Administrative Assistant III', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (193, 9, 187, 'Senior Sales Associate', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (194, 1, 97, 'Dental Hygienist', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (195, 5, 492, 'Technical Writer', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (196, 2, 122, 'Environmental Tech', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (197, 1, 162, 'Staff Accountant III', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (198, 3, 434, 'Registered Nurse', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (199, 5, 111, 'Software Test Engineer II', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (200, 9, 187, 'Recruiter', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (201, 6, 123, 'VP Product Management', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (202, 3, 435, 'Teacher', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (203, 10, 79, 'Senior Developer', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (204, 4, 273, 'Biostatistician I', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (205, 9, 176, 'Product Engineer', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (206, 8, 281, 'Staff Accountant I', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (207, 7, 226, 'Assistant Manager', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (208, 4, 75, 'Geologist II', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (209, 2, 253, 'Junior Executive', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (210, 2, 451, 'Assistant Professor', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (211, 3, 261, 'Community Outreach Specialist', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (212, 9, 149, 'Librarian', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (213, 1, 1, 'VP Product Management', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (214, 5, 441, 'Product Engineer', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (215, 10, 425, 'Assistant Media Planner', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (216, 10, 121, 'Computer Systems Analyst II', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (217, 7, 175, 'Senior Quality Engineer', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (218, 5, 252, 'Chemical Engineer', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (219, 7, 91, 'Computer Systems Analyst II', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (220, 10, 463, 'Human Resources Assistant II', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (221, 2, 12, 'Internal Auditor', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (222, 9, 138, 'Health Coach IV', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (223, 5, 235, 'Chief Design Engineer', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (224, 9, 495, 'Paralegal', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (225, 6, 18, 'Financial Advisor', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (226, 8, 49, 'Pharmacist', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (227, 7, 389, 'Environmental Specialist', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (228, 5, 447, 'Environmental Tech', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (229, 4, 394, 'Safety Technician I', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (230, 9, 285, 'Administrative Assistant III', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (231, 7, 99, 'Assistant Professor', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (232, 5, 125, 'Staff Accountant IV', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (233, 7, 49, 'Project Manager', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (234, 1, 371, 'Biostatistician II', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (235, 5, 63, 'Web Designer I', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (236, 1, 395, 'Geological Engineer', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (237, 2, 227, 'Assistant Manager', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (238, 3, 192, 'VP Product Management', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (239, 3, 250, 'Technical Writer', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (240, 4, 498, 'Pharmacist', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (241, 6, 130, 'Payment Adjustment Coordinator', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (242, 8, 346, 'Programmer Analyst III', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (243, 6, 189, 'Software Test Engineer I', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (244, 10, 179, 'Safety Technician IV', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (245, 5, 295, 'Developer III', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (246, 9, 192, 'Automation Specialist IV', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (247, 8, 315, 'Accounting Assistant IV', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (248, 5, 76, 'Associate Professor', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (249, 3, 214, 'Environmental Specialist', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (250, 4, 56, 'Financial Analyst', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (251, 4, 307, 'Web Developer I', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (252, 9, 483, 'Professor', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (253, 2, 481, 'Geologist I', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (254, 4, 348, 'Web Developer IV', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (255, 2, 370, 'Software Consultant', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (256, 6, 16, 'Research Associate', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (257, 2, 144, 'Librarian', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (258, 2, 484, 'Registered Nurse', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (259, 4, 8, 'Account Coordinator', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (260, 9, 54, 'Human Resources Assistant IV', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (261, 8, 344, 'Programmer Analyst III', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (262, 8, 279, 'Accountant I', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (263, 3, 37, 'Chief Design Engineer', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (264, 5, 484, 'Senior Cost Accountant', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (265, 2, 353, 'Account Coordinator', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (266, 10, 388, 'Operator', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (267, 9, 338, 'Nuclear Power Engineer', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (268, 4, 175, 'Account Representative II', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (269, 3, 78, 'Senior Developer', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (270, 7, 231, 'Project Manager', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (271, 6, 391, 'Engineer IV', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (272, 3, 119, 'Nurse', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (273, 8, 31, 'Web Designer I', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (274, 7, 350, 'Teacher', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (275, 3, 137, 'Automation Specialist IV', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (276, 5, 68, 'Recruiting Manager', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (277, 6, 179, 'Food Chemist', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (278, 4, 120, 'Software Engineer IV', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (279, 5, 66, 'Accounting Assistant IV', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (280, 5, 357, 'Environmental Specialist', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (281, 8, 74, 'Structural Analysis Engineer', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (282, 1, 119, 'Registered Nurse', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (283, 7, 185, 'Chief Design Engineer', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (284, 9, 182, 'Geologist I', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (285, 2, 371, 'VP Product Management', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (286, 3, 215, 'Physical Therapy Assistant', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (287, 1, 29, 'Nurse Practicioner', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (288, 5, 65, 'Food Chemist', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (289, 4, 235, 'Accounting Assistant III', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (290, 7, 23, 'Nuclear Power Engineer', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (291, 4, 485, 'Office Assistant III', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (292, 9, 233, 'Biostatistician III', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (293, 5, 479, 'Account Executive', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (294, 1, 194, 'Office Assistant I', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (295, 1, 440, 'Chemical Engineer', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (296, 9, 23, 'Developer III', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (297, 8, 31, 'VP Marketing', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (298, 5, 344, 'Geological Engineer', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (299, 5, 401, 'Environmental Tech', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (300, 3, 393, 'Human Resources Manager', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (301, 3, 12, 'Administrative Assistant III', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (302, 10, 200, 'Database Administrator II', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (303, 7, 9, 'Programmer Analyst II', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (304, 8, 316, 'Mechanical Systems Engineer', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (305, 3, 498, 'Actuary', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (306, 9, 408, 'Account Coordinator', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (307, 3, 267, 'Biostatistician III', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (308, 4, 318, 'Senior Sales Associate', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (309, 1, 148, 'Financial Analyst', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (310, 7, 500, 'Help Desk Operator', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (311, 10, 317, 'Analyst Programmer', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (312, 6, 201, 'Design Engineer', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (313, 2, 257, 'Financial Advisor', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (314, 4, 274, 'Quality Engineer', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (315, 1, 202, 'Assistant Manager', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (316, 6, 1, 'Software Consultant', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (317, 1, 186, 'Paralegal', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (318, 4, 300, 'Structural Analysis Engineer', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (319, 6, 400, 'Legal Assistant', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (320, 8, 5, 'Information Systems Manager', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (321, 3, 221, 'Web Designer II', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (322, 1, 41, 'Electrical Engineer', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (323, 2, 180, 'Senior Editor', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (324, 8, 28, 'Payment Adjustment Coordinator', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (325, 8, 332, 'Programmer II', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (326, 4, 99, 'Clinical Specialist', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (327, 2, 283, 'Quality Control Specialist', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (328, 3, 471, 'Human Resources Manager', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (329, 3, 233, 'VP Product Management', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (330, 7, 323, 'Nuclear Power Engineer', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (331, 6, 403, 'Human Resources Assistant IV', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (332, 5, 377, 'Environmental Specialist', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (333, 6, 379, 'Programmer Analyst I', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (334, 8, 3, 'Office Assistant IV', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (335, 8, 14, 'Senior Editor', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (336, 10, 315, 'Design Engineer', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (337, 8, 168, 'Sales Representative', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (338, 10, 80, 'Recruiting Manager', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (339, 8, 113, 'Internal Auditor', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (340, 2, 466, 'Systems Administrator I', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (341, 5, 113, 'Environmental Specialist', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (342, 4, 228, 'Account Coordinator', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (343, 4, 398, 'VP Accounting', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (344, 10, 320, 'Registered Nurse', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (345, 5, 420, 'Research Associate', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (346, 9, 149, 'Office Assistant I', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (347, 2, 423, 'Senior Sales Associate', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (348, 8, 402, 'Senior Sales Associate', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (349, 2, 43, 'Systems Administrator IV', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (350, 2, 443, 'Business Systems Development Analyst', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (351, 4, 227, 'Design Engineer', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (352, 9, 419, 'Administrative Assistant II', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (353, 5, 190, 'Design Engineer', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (354, 10, 226, 'Health Coach III', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (355, 1, 92, 'Account Representative III', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (356, 6, 406, 'Human Resources Assistant II', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (357, 8, 249, 'Assistant Professor', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (358, 8, 184, 'Marketing Assistant', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (359, 3, 190, 'Food Chemist', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (360, 6, 214, 'Junior Executive', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (361, 4, 354, 'Product Engineer', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (362, 7, 77, 'Social Worker', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (363, 4, 403, 'Nurse Practicioner', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (364, 6, 397, 'Software Consultant', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (365, 3, 78, 'Clinical Specialist', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (366, 8, 196, 'GIS Technical Architect', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (367, 10, 183, 'Quality Control Specialist', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (368, 6, 404, 'Chief Design Engineer', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (369, 1, 228, 'Programmer Analyst II', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (370, 6, 111, 'VP Sales', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (371, 4, 383, 'Structural Analysis Engineer', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (372, 8, 273, 'Budget/Accounting Analyst III', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (373, 4, 84, 'Senior Sales Associate', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (374, 7, 220, 'Help Desk Operator', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (375, 5, 204, 'Analog Circuit Design manager', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (376, 5, 488, 'Account Representative IV', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (377, 7, 170, 'General Manager', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (378, 3, 472, 'Chemical Engineer', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (379, 4, 449, 'Budget/Accounting Analyst II', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (380, 8, 152, 'Associate Professor', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (381, 7, 242, 'Systems Administrator IV', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (382, 4, 136, 'Senior Financial Analyst', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (383, 9, 48, 'Assistant Manager', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (384, 6, 323, 'Chemical Engineer', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (385, 3, 76, 'Programmer Analyst II', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (386, 1, 137, 'Help Desk Technician', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (387, 6, 437, 'Food Chemist', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (388, 6, 255, 'Software Engineer IV', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (389, 3, 107, 'Developer I', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (390, 9, 336, 'Editor', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (391, 7, 110, 'Legal Assistant', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (392, 4, 281, 'Assistant Media Planner', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (393, 4, 126, 'Computer Systems Analyst II', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (394, 3, 69, 'Senior Financial Analyst', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (395, 9, 281, 'Sales Representative', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (396, 4, 28, 'Cost Accountant', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (397, 9, 129, 'Environmental Tech', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (398, 10, 365, 'Web Developer II', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (399, 9, 486, 'Administrative Officer', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (400, 3, 474, 'Mechanical Systems Engineer', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (401, 2, 458, 'Automation Specialist II', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (402, 5, 39, 'Media Manager IV', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (403, 6, 446, 'Office Assistant III', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (404, 6, 247, 'Research Nurse', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (405, 1, 151, 'Design Engineer', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (406, 9, 296, 'VP Accounting', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (407, 5, 95, 'Web Designer I', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (408, 10, 262, 'Research Nurse', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (409, 1, 175, 'Database Administrator II', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (410, 1, 230, 'Programmer Analyst III', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (411, 5, 72, 'Geologist IV', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (412, 2, 323, 'Speech Pathologist', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (413, 8, 441, 'Developer IV', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (414, 7, 32, 'Electrical Engineer', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (415, 3, 297, 'Chief Design Engineer', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (416, 2, 420, 'Financial Advisor', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (417, 9, 374, 'Office Assistant I', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (418, 1, 193, 'Web Designer IV', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (419, 3, 357, 'Junior Executive', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (420, 6, 412, 'Nurse Practicioner', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (421, 5, 304, 'Data Coordiator', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (422, 8, 107, 'Account Coordinator', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (423, 4, 403, 'Developer II', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (424, 7, 344, 'Tax Accountant', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (425, 9, 377, 'Registered Nurse', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (426, 1, 201, 'Sales Representative', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (427, 1, 24, 'Software Consultant', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (428, 7, 323, 'Product Engineer', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (429, 6, 247, 'Nurse', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (430, 1, 153, 'Operator', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (431, 9, 24, 'Structural Engineer', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (432, 2, 409, 'Software Engineer II', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (433, 6, 429, 'Software Test Engineer II', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (434, 6, 85, 'Business Systems Development Analyst', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (435, 1, 461, 'Social Worker', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (436, 8, 433, 'Data Coordiator', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (437, 10, 239, 'Analyst Programmer', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (438, 10, 72, 'Web Designer III', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (439, 6, 417, 'Human Resources Assistant III', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (440, 8, 90, 'Systems Administrator IV', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (441, 6, 285, 'Paralegal', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (442, 1, 82, 'Legal Assistant', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (443, 6, 255, 'Account Executive', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (444, 3, 36, 'Systems Administrator II', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (445, 6, 139, 'Quality Engineer', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (446, 4, 350, 'Editor', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (447, 4, 283, 'Programmer Analyst III', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (448, 5, 344, 'Help Desk Technician', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (449, 4, 146, 'Health Coach III', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (450, 5, 290, 'Staff Accountant I', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (451, 9, 68, 'Internal Auditor', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (452, 9, 42, 'Database Administrator III', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (453, 3, 461, 'Chief Design Engineer', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (454, 4, 440, 'Web Developer IV', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (455, 6, 349, 'Executive Secretary', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (456, 5, 135, 'Compensation Analyst', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (457, 5, 152, 'Marketing Assistant', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (458, 6, 227, 'Quality Control Specialist', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (459, 5, 357, 'Senior Developer', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (460, 4, 40, 'Sales Representative', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (461, 2, 193, 'Actuary', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (462, 4, 135, 'Associate Professor', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (463, 5, 86, 'Product Engineer', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (464, 6, 297, 'Electrical Engineer', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (465, 10, 259, 'Human Resources Assistant IV', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (466, 7, 307, 'Chief Design Engineer', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (467, 3, 151, 'Staff Accountant II', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (468, 7, 261, 'Chemical Engineer', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (469, 6, 197, 'Tax Accountant', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (470, 9, 463, 'Social Worker', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (471, 10, 440, 'Design Engineer', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (472, 4, 191, 'Quality Control Specialist', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (473, 3, 432, 'Food Chemist', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (474, 8, 260, 'Administrative Assistant IV', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (475, 7, 429, 'Senior Developer', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (476, 9, 13, 'Paralegal', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (477, 3, 167, 'Web Designer IV', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (478, 10, 208, 'Payment Adjustment Coordinator', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (479, 4, 136, 'Legal Assistant', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (480, 7, 183, 'Tax Accountant', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (481, 4, 148, 'Librarian', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (482, 10, 293, 'Quality Control Specialist', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (483, 10, 286, 'Analyst Programmer', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (484, 1, 219, 'Software Engineer IV', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (485, 5, 338, 'Web Designer I', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (486, 3, 203, 'Sales Associate', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (487, 2, 347, 'Environmental Specialist', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (488, 9, 490, 'Administrative Assistant IV', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (489, 5, 305, 'Staff Scientist', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (490, 1, 402, 'Senior Cost Accountant', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (491, 5, 101, 'Nuclear Power Engineer', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (492, 4, 22, 'Research Assistant IV', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (493, 2, 371, 'Programmer Analyst IV', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (494, 6, 240, 'Media Manager III', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (495, 5, 442, 'Research Nurse', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (496, 3, 473, 'Executive Secretary', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (497, 6, 407, 'Legal Assistant', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (498, 8, 345, 'Legal Assistant', 2022);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (499, 7, 74, 'Senior Financial Analyst', 2021);
insert into house_staff (id, house_id, staff_id, function, schoolyear) values (500, 6, 276, 'Data Coordiator', 2022);
