insert into houses (id, name, house_number, schoolyear) values (1, 'Nebraska', 6, 2022);
insert into houses (id, name, house_number, schoolyear) values (2, 'Texas', 1, 2022);
insert into houses (id, name, house_number, schoolyear) values (3, 'Texas', 5, 2022);
insert into houses (id, name, house_number, schoolyear) values (4, 'Nevada', 9, 2021);
insert into houses (id, name, house_number, schoolyear) values (5, 'California', 4, 2021);
insert into houses (id, name, house_number, schoolyear) values (6, 'North Carolina', 9, 2021);
insert into houses (id, name, house_number, schoolyear) values (7, 'District of Columbia', 5, 2022);
insert into houses (id, name, house_number, schoolyear) values (8, 'Mississippi', 2, 2022);
insert into houses (id, name, house_number, schoolyear) values (9, 'Texas', 9, 2021);
insert into houses (id, name, house_number, schoolyear) values (10, 'Utah', 1, 2022);
